#include<iostream.h>
#include<conio.h>
void fact(){
}
void sod(){
}
void solf(){
}
void rev(){
}
void arm(){
}
void main(){
int a = 0;
do{
clrscr();
cout<<"1. factoral\n2. sum of all digit\n3. sum of last and first digit\n4. reverse\n5. armstrong number\n6. exit";
 cout<<"\nenter a number : ";
 cin>>a;
 cout<<"enter a number : "
 cin>>ans;
 switch(a){
 case 1:
 break;
 case 2:
 break;
 case 3:
 break;
 case 4:
 break;
 case 5:
 break;
 }

 }while(a<6);
}